Repository configu/configu, pull requests merged in 2022-11, with the labels that each got.

#27 Rename cli store command flag to --uri
  ts/packages/cli/src/commands/store.ts
Labels: chore

#26 Store logic refactor
  jtd/Set.jtd.json
  jtd/Store.jtd.json
  ts/package-lock.json
  ts/packages/node/src/stores/AwsSecretsManager.ts
  ts/packages/node/src/stores/HashiCorpVault.ts
  ts/packages/node/src/stores/JsonFile.ts
  ts/packages/ts/package.json
  ts/packages/ts/src/Set.ts
  ts/packages/ts/src/Store.ts
  ts/packages/ts/src/commands/DeleteCommand.ts
  ts/packages/ts/src/commands/EvalCommand.ts
  ts/packages/ts/src/commands/UpsertCommand.ts
  ts/packages/ts/src/index.ts
  ts/packages/ts/src/stores/Configu.ts
  ts/packages/ts/src/stores/KeyValue.ts
  ts/packages/ts/src/stores/Noop.ts
  ts/packages/ts/src/types/generated/Set.jtd.json
  ts/packages/ts/src/types/generated/Set.ts
  ts/packages/ts/src/types/generated/Store.jtd.json
  ts/packages/ts/src/types/generated/Store.ts
  ts/packages/ts/src/types/index.ts
  ts/packages/ts/src/utils.ts
  ts/tsconfig.json
Labels: feat

#28 Refactor AWS secret manager store to use KVstore
  ts/packages/node/src/stores/AwsSecretsManager.ts
Labels: chore

#29 Refactor Hashicorp Vault to use KVstore
  ts/packages/node/src/stores/HashiCorpVault.ts
Labels: chore

#35 Refactor store class to include initialization logic
  ts/packages/node/src/stores/AwsSecretsManager.ts
  ts/packages/node/src/stores/HashiCorpVault.ts
  ts/packages/node/src/stores/JsonFile.ts
  ts/packages/ts/src/Store.ts
  ts/packages/ts/src/stores/Configu.ts
  ts/packages/ts/src/stores/KeyValue.ts
Labels: chore

#31 Implement Kubernetes Secret store
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/KubernetesSecret.ts
Labels: feat

#30 Implement GCP Secret Manager store
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/GcpSecretManager.ts
Labels: feat

#33 Implement Localforage store
  ts/package-lock.json
  ts/packages/browser/package.json
  ts/packages/browser/src/stores/Localforage.ts
Labels: feat

#45 Fix store protocols to schemes
  ts/packages/node/src/stores/GcpSecretManager.ts
  ts/packages/node/src/stores/KubernetesSecret.ts
Labels: bug

#49 Fix CFGU templates escaping texts unintentionally
  ts/packages/ts/src/utils.ts
Labels: bug

#47 Fix JSON to Kubernetes config formatter
  ts/packages/lib/src/formatters/configFormatters.ts
Labels: bug

#43 Change CLI URL usage to URI
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/delete.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/store.ts
  ts/packages/cli/src/commands/upsert.ts
  ts/packages/cli/src/helpers/stores/AwsSecretsManager.ts
  ts/packages/cli/src/helpers/stores/Configu.ts
  ts/packages/cli/src/helpers/stores/HashiCorpVault.ts
  ts/packages/cli/src/helpers/stores/JsonFile.ts
  ts/packages/cli/src/helpers/stores/Noop.ts
  ts/packages/cli/src/helpers/stores/index.ts
  ts/packages/cli/src/helpers/stores/types.ts
Labels: chore

#54 Fix store UID generation on eval command
  ts/packages/ts/src/commands/EvalCommand.ts
Labels: bug

#56 Rename ORM store class
  ts/packages/node/src/stores/AuroraMysql.ts
  ts/packages/node/src/stores/AuroraPostgreSQL.ts
  ts/packages/node/src/stores/CockroachDB.ts
  ts/packages/node/src/stores/MSSQL.ts
  ts/packages/node/src/stores/MariaDB.ts
  ts/packages/node/src/stores/MySQL.ts
  ts/packages/node/src/stores/ORM.ts
  ts/packages/node/src/stores/PostgreSQL.ts
  ts/packages/node/src/stores/SQLite.ts
Labels: chore

#57 Change GCP project ID naming
  ts/packages/node/src/stores/GcpSecretManager.ts
Labels: chore

#51 Implement CLI support for ORM stores
  ts/packages/cli/src/helpers/stores/ORM.ts
  ts/packages/cli/src/helpers/stores/index.ts
  ts/packages/cli/src/helpers/stores/types.ts
Labels: feat
