Repository configu/configu, pull requests merged in 2022-10, with the labels that each got.

#1 Add NoopStore
  ts/packages/node/src/index.ts
  ts/packages/ts/src/index.ts
  ts/packages/ts/src/stores/Noop.ts
  ts/tsconfig.build.json
Labels: feat

#2 Add --defaults to export command with NoopStore
  .github/workflows/cd-cli.yml
  .vscode/launch.json
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/helpers/stores/Noop.ts
  ts/packages/cli/src/helpers/stores/index.ts
Labels: feat

#3 Improve Cfgu class
  jtd/Cfgu.jtd.json
  ts/packages/node/src/Cfgu.ts
  ts/packages/ts/src/Cfgu.ts
  ts/packages/ts/src/commands/EvalCommand.ts
  ts/packages/ts/src/commands/UpsertCommand.ts
  ts/packages/ts/src/index.ts
  ts/packages/ts/src/types/generated/Cfgu.jtd.json
  ts/packages/ts/src/types/generated/Cfgu.ts
Labels: feat

#4 Bump @configu/ts
  ts/package-lock.json
  ts/package.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/init.ts
Labels: chore

#5 Add validate function to JTD
  ts/packages/ts/src/types/index.ts
  ts/packages/ts/src/utils.ts
Labels: feat

#6 Wrap JTD validate logic
  ts/packages/ts/src/utils.ts
Labels: chore

#12 Add error wrapper around runtime sync on CLI export
  ts/packages/cli/src/helpers/synchronizers/index.ts
Labels: chore

#7 Implement Netlify runtime integration
  ts/packages/cli/src/helpers/synchronizers/logic/Netlify.ts
  ts/packages/cli/src/helpers/synchronizers/logic/index.ts
Labels: feat

#9 Implement Vercel runtime integration
  ts/packages/cli/src/helpers/synchronizers/logic/Vercel.ts
  ts/packages/cli/src/helpers/synchronizers/logic/index.ts
Labels: feat

#8 Implement GCP Cloud Functions runtime integration
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/helpers/synchronizers/logic/GcpCloudFunctions.ts
  ts/packages/cli/src/helpers/synchronizers/logic/index.ts
Labels: feat

#10 Implement Azure Functions runtime integration
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/helpers/synchronizers/logic/AzureFunctions.ts
  ts/packages/cli/src/helpers/synchronizers/logic/index.ts
Labels: feat

#11 Implement AWS ECS runtime integration
  ts/packages/cli/src/helpers/synchronizers/logic/AwsEcs.ts
  ts/packages/cli/src/helpers/synchronizers/logic/index.ts
Labels: feat

#13 Align Configu store with Configu API auth mechanism
  .vscode/launch.json
  ts/packages/ts/src/stores/Configu.ts
Labels: chore

#14 Bump cli deps
  ts/package-lock.json
  ts/packages/cli/package.json
Labels: chore

#15 Add reserved names to cfgu
  ts/packages/ts/src/Cfgu.ts
Labels: chore

#16 Add secrets and cicd integration globals
  ts/package-lock.json
  ts/packages/lib/package.json
  ts/packages/lib/src/index.ts
  ts/packages/lib/src/integrations/cicd.ts
  ts/packages/lib/src/integrations/index.ts
  ts/packages/lib/src/integrations/secrets.ts
Labels: feat

#17 Publish @configu/browser sdk
  .github/workflows/cd-ts.yml
  ts/package-lock.json
  ts/packages/browser/package.json
  ts/packages/browser/src/Cfgu.ts
  ts/packages/browser/src/index.ts
  ts/tsconfig.build.json
  ts/tsconfig.json
Labels: feat

#18 Fix browser sdk accepted extensions
  ts/packages/browser/src/Cfgu.ts
Labels: bug

#19 Add description to cli's commands and flags
  .github/actions/ts-env-action/action.yml
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/delete.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/store.ts
  ts/packages/cli/src/commands/upsert.ts
Labels: chore

#20 Add "multiple" parameter to Cfgu init in the browser SDK
  ts/packages/browser/src/Cfgu.ts
Labels: chore

#21 Bump configu dependencies
  ts/package-lock.json
  ts/packages/cli/package.json
Labels: chore

#22 Browser SDK Cfgu init() & initBulk()
  ts/packages/browser/src/Cfgu.ts
Labels: chore
