Repository configu/configu, pull requests merged in 2023-10, with the labels that each got.

#284 Enhance CLI Installation Scripts
  ts/packages/cli/scripts/install.ps1
  ts/packages/cli/scripts/install.sh
Labels: chore

#278 fix: redirecting Recipes in docs
  README.md
Labels: bug, hacktoberfest-accepted

#288 Added Gitpod to the Repository and Button link in readme
  .gitpod.yml
  README.md
Labels: chore, hacktoberfest-accepted

#253 Implement `compact` config formatters
  ts/packages/lib/src/formatters/ConfigFormat.ts
  ts/packages/lib/src/formatters/configFormatters.ts
Labels: feat, hacktoberfest-accepted

#287 Added Discord Badge to Readme file
  README.md
Labels: chore

#255 Refactor `ConfigSchema`
  ts/package-lock.json
  ts/packages/browser/package.json
  ts/packages/browser/src/ConfigSchema.ts
  ts/packages/browser/src/index.ts
  ts/packages/node/src/ConfigSchema.ts
  ts/packages/node/src/commands/ExportCommand.ts
  ts/packages/node/src/index.ts
  ts/packages/node/src/playground.ts
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/ConfigSet.ts
  ts/packages/ts/src/commands/DeleteCommand.ts
  ts/packages/ts/src/commands/EvalCommand.ts
  ts/packages/ts/src/commands/TestCommand.ts
  ts/packages/ts/src/commands/UpsertCommand.ts
  ts/packages/ts/src/commands/commands.test.ts
  ts/packages/ts/src/playground.test.ts
  ts/packages/ts/src/types/generated.ts
  ts/packages/ts/src/types/index.ts
  ts/packages/ts/src/types/types.test.ts
  ts/packages/ts/src/utils.test.ts
  ts/packages/ts/src/utils.ts
  types/ConfigSchema.ts
  types/ConfigStore.ts
Labels: chore
