Repository configu/configu, pull requests merged in 2023-06, with the labels that each got.

#110 TestCommand for ConfigStore
  ts/packages/cli/src/commands/test.ts
  ts/packages/ts/src/commands/TestCommand.ts
  ts/packages/ts/src/index.ts
Labels: feat

#113 TestCommand for @configu/node
  ts/packages/cli/src/commands/test.ts
  ts/packages/node/src/index.ts
Labels: chore

#114 TestCommand for cli from @configu/node
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/test.ts
Labels: chore

#112 Usability upgrade
  package-lock.json
  package.json
  ts/.eslintrc
  ts/package-lock.json
  ts/package.json
  ts/packages/browser/package.json
  ts/packages/browser/src/index.ts
  ts/packages/browser/src/stores/LocalForage.ts
  ts/packages/cli/scripts/enforce.sh
  ts/packages/lib/package.json
  ts/packages/node/package.json
  ts/packages/node/src/commands/ExportCommand.ts
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/AwsSecretsManager.ts
  ts/packages/node/src/stores/AzureKeyVault.ts
  ts/packages/node/src/stores/CockroachDB.ts
  ts/packages/node/src/stores/GcpSecretManager.ts
  ts/packages/node/src/stores/HashiCorpVault.ts
  ts/packages/node/src/stores/JsonFile.ts
  ts/packages/node/src/stores/KubernetesSecret.ts
  ts/packages/node/src/stores/MSSQL.ts
  ts/packages/node/src/stores/MariaDB.ts
  ts/packages/node/src/stores/MySQL.ts
  ts/packages/node/src/stores/ORM.ts
  ts/packages/node/src/stores/PostgreSQL.ts
  ts/packages/node/src/stores/SQLite.ts
  ts/packages/ts/package.json
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/commands/EvalCommand.ts
  ts/packages/ts/src/commands/ExportCommand.ts
  ts/packages/ts/src/commands/TestCommand.ts
  ts/packages/ts/src/commands/commands.test.ts
  ts/packages/ts/src/index.ts
  ts/packages/ts/src/stores/Configu.test.ts
  ts/packages/ts/src/stores/Configu.ts
  ts/packages/ts/src/stores/InMemory.ts
  ts/packages/ts/src/stores/KeyValue.ts
  ts/packages/ts/src/stores/Noop.ts
  ts/packages/ts/src/utils.test.ts
  ts/packages/ts/src/utils.ts
Labels: feat

#115 Usability upgrade
  ts/package-lock.json
  ts/package.json
  ts/packages/cli/package.json
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/delete.ts
  ts/packages/cli/src/commands/eval.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/init.ts
  ts/packages/cli/src/commands/login.ts
  ts/packages/cli/src/commands/store/delete.ts
  ts/packages/cli/src/commands/store/list.ts
  ts/packages/cli/src/commands/store/upsert.ts
  ts/packages/cli/src/commands/test.ts
  ts/packages/cli/src/commands/upsert.ts
  ts/packages/cli/src/helpers/stores.ts
  ts/packages/cli/src/helpers/stores/Configu.ts
  ts/packages/cli/src/helpers/stores/default.ts
  ts/packages/cli/src/helpers/stores/index.ts
  ts/packages/cli/src/helpers/utils.ts
  ts/packages/lib/package.json
  ts/packages/lib/src/formatters/configFormatters.ts
  ts/packages/lib/src/integrations/store.test.ts
  ts/packages/lib/src/integrations/store.ts
  ts/packages/node/src/index.ts
  ts/packages/ts/src/commands/EvalCommand.ts
Labels: feat

#116 Usability upgrade
  README.md
  ts/package-lock.json
  ts/packages/browser/src/stores/LocalForage.ts
  ts/packages/cli/.eslintrc
  ts/packages/cli/package.json
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/eval.ts
  ts/packages/cli/src/commands/login.ts
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/AWSSecretsManager.ts
  ts/packages/node/src/stores/AzureKeyVault.ts
  ts/packages/node/src/stores/CockroachDB.ts
  ts/packages/node/src/stores/Configu.ts
  ts/packages/node/src/stores/GCPSecretManager.ts
  ts/packages/node/src/stores/HashiCorpVault.ts
  ts/packages/node/src/stores/JsonFile.ts
  ts/packages/node/src/stores/KubernetesSecret.ts
  ts/packages/node/src/stores/MSSQL.ts
  ts/packages/node/src/stores/MariaDB.ts
  ts/packages/node/src/stores/MySQL.ts
  ts/packages/node/src/stores/PostgreSQL.ts
  ts/packages/node/src/stores/SQLite.ts
  ts/packages/ts/src/stores/Configu.ts
Labels: feat

#118 Usability upgrade
  ts/package-lock.json
  ts/packages/cli/package.json
Labels: feat

#119 fix(cli): GCPSecretManagerConfigStore
  ts/packages/cli/src/helpers/stores.ts
Labels: bug

#120 fix(cli): getStoreInstanceByStoreFlag
  ts/packages/cli/src/base.ts
  ts/packages/node/src/stores/AWSSecretsManager.ts
Labels: bug

#121 CLI usability upgrades
  ts/packages/cli/scripts/enforce.sh
  ts/packages/cli/scripts/verify.sh
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/run.ts
  ts/packages/cli/src/commands/test.ts
Labels: feat

#123 Improve cli docs
  .github/workflows/cd-cli.yml
  ts/package-lock.json
  ts/packages/cli/README.md
  ts/packages/cli/package.json
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/delete.ts
  ts/packages/cli/src/commands/eval.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/init.ts
  ts/packages/cli/src/commands/login.ts
  ts/packages/cli/src/commands/run.ts
  ts/packages/cli/src/commands/test.ts
  ts/packages/cli/src/commands/upsert.ts
  ts/packages/cli/src/helpers/utils.ts
Labels: chore

#125 Improve repo content
  .github/workflows/cd-cli.yml
  CONTRIBUTING.md
  README.md
  java/src/index.java
  package-lock.json
  package.json
  py/README.md
  ts/packages/browser/README.md
  ts/packages/cli/README.md
  ts/packages/cli/manifest.tmpl.md
  ts/packages/cli/package.json
  ts/packages/node/README.md
Labels: chore

#130 Update the python SDK with the changes in ts/node SDKs
  examples/py-sdk/main.py
  py/README.md
  py/configu/__init__.py
  py/configu/commands/__init__.py
  py/configu/commands/eval_command.py
  py/configu/commands/export_command.py
  py/configu/commands/upsert_command.py
  py/configu/core/command.py
  py/configu/core/config_schema.py
  py/configu/stores/__init__.py
  py/configu/stores/configu_store.py
  py/configu/stores/in_memory_store.py
  py/configu/stores/json_file_store.py
  py/configu/utils.py
  py/tests/test_model.py
Labels: feat

#134 Fix key:value set() and remove wildcards from py
  py/configu/stores/aws_secrets_manager_store.py
  py/configu/stores/configu_store.py
  py/configu/stores/json_file_store.py
  py/configu/stores/key_value_store.py
  ts/packages/ts/src/stores/KeyValue.ts
Labels: feat
