Repository configu/configu, pull requests merged in 2023-08, with the labels that each got.

#179 Add AWS Parameter Store to @configu/cli stores
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/helpers/stores.ts
Labels: chore

#183 Fix `KeyValue` `ConfigStore` set method
  ts/packages/ts/src/stores/KeyValue.ts
Labels: bug

#172 Implement LaunchDarkly ConfigStore
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/LaunchDarkly.ts
Labels: feat

#186 Add LaunchDarkly to @configu/lib
  ts/packages/lib/src/integrations/store.ts
Labels: chore

#187 Add LaunchDarkly Store to @configu/cli stores
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/helpers/stores.ts
Labels: chore

#188 Fix validation of empty value during evaluation in @configu/ts
  ts/packages/ts/src/commands/EvalCommand.ts
Labels: bug

#180 Implement `DockerImage` `Cfgu type` in @configu/ts
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat

#167 Implement `Keyv` `ConfigStore` in @configu/node
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/stores/Keyv.ts
Labels: feat

#189 Bump `@configu/ts` and `@configu/node` to 0.17.0
  ts/package-lock.json
  ts/packages/cli/package.json
Labels: chore

#163 Python SDK refactoring
  examples/py-sdk/main.py
  py/.flake8
  py/DOCS.md
  py/README.md
  py/configu/__init__.py
  py/configu/commands/__init__.py
  py/configu/commands/eval_command.py
  py/configu/commands/export_command.py
  py/configu/commands/upsert_command.py
  py/configu/core/__init__.py
  py/configu/core/command.py
  py/configu/core/config_schema.py
  py/configu/core/config_set.py
  py/configu/core/config_store.py
  py/configu/stores/__init__.py
  py/configu/stores/aws_secrets_manager_store.py
  py/configu/stores/azure_key_vault_store.py
  py/configu/stores/configu_store.py
  py/configu/stores/gcp_secret_manager.py
  py/configu/stores/in_memory_store.py
  py/configu/stores/json_file_store.py
  py/configu/stores/key_value_store.py
  py/configu/stores/kubernetes_secret_store.py
  py/configu/utils.py
  py/poetry.lock
  py/pyproject.toml
Labels: chore

#216 Move `Keyv` to dependencies from dev dependencies
  ts/package-lock.json
  ts/packages/node/package.json
Labels: chore

#206 Implement `MACAddress` `Cfgu Type`
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat

#196 Fix `DockerImage` type regex
  ts/packages/ts/src/ConfigSchema.ts
Labels: bug

#203 Implement `MIMEType` `Cfgu Type`
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat

#205 Implement `CloudRegionTypes` `Cfgu Type`
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat

#200 Implement `Language` `Cfgu Type`
  ts/package-lock.json
  ts/packages/ts/package.json
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat

#217 Update generated.ts and reformat `ConfigSchema`
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
Labels: chore

#219 Bump `@configu/ts` and `@configu/node` from 0.17 to 0.18
  ts/package-lock.json
  ts/packages/cli/package.json
Labels: chore

#225 General chores and fixes
  .github/actions/go-env-action/action.yml
  .github/workflows/cd-cra.yml
  .github/workflows/cd-go.yml
  .github/workflows/cd-py.yml
  .github/workflows/ci-go-test.yml
  .github/workflows/ci-ts-test.yml
  .vscode/launch.json
  README.md
  assets/favicon.ico
  assets/icon.png
  assets/icon.svg
  examples/create-react-app/create-react-app.cfgu.json
  go/generated.go
  package-lock.json
  package.json
  py/configu/core/generated.py
  ts/.eslintrc
  ts/.prettierrc
  ts/package-lock.json
  ts/package.json
  ts/packages/browser/package.json
  ts/packages/cli/package.json
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/find.ts
  ts/packages/cli/src/commands/init.ts
  ts/packages/cli/src/commands/login.ts
  ts/packages/cli/src/commands/run.ts
  ts/packages/lib/package.json
  ts/packages/lib/src/index.ts
  ts/packages/lib/src/schemas/foo.ts
  ts/packages/lib/src/schemas/getStarted.ts
  ts/packages/lib/src/schemas/index.ts
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/Configu.ts
  ts/packages/node/src/stores/LaunchDarkly.ts
  ts/packages/ts/package.json
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/vscode/public/cfgu.schema.json
Labels: chore

#228 CLI chores
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/base.ts
  ts/packages/cli/src/commands/delete.ts
  ts/packages/cli/src/commands/eval.ts
  ts/packages/cli/src/commands/export.ts
  ts/packages/cli/src/commands/find.ts
  ts/packages/cli/src/commands/init.ts
  ts/packages/cli/src/commands/test.ts
  ts/packages/cli/src/commands/upsert.ts
Labels: chore

#231 Terraform example
  examples/terraform/.gitignore
  examples/terraform/.terraform.lock.hcl
  examples/terraform/README.md
  examples/terraform/main.tf
  examples/terraform/outputs.tf
  examples/terraform/terraform-outputs.cfgu.json
  examples/terraform/terraform-variables.cfgu.json
  examples/terraform/variables.tf
  ts/packages/lib/src/formatters/configFormatters.ts
Labels: documentation

#223 Implement `DateTime` `Cfgu Type`
  go/generated.go
  py/configu/core/generated.py
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/types/generated.ts
  ts/packages/vscode/public/cfgu.schema.json
  types/Cfgu.ts
Labels: feat

#181 Implement `INI` `ConfigStore`
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/IniFile.test.ts
  ts/packages/node/src/stores/IniFile.ts
Labels: feat

#220 Catch-up python CFGU types with ts
  py/configu/core/config_schema.py
  py/poetry.lock
  py/pyproject.toml
Labels: chore

#222 Implement fallback exception when cfgu-type doesn't have a validator function
  py/configu/commands/eval_command.py
  py/configu/commands/upsert_command.py
  py/configu/core/config_schema.py
Labels: chore
