Repository configu/configu, pull requests merged in 2023-09, with the labels that each got.

#234 Added `Keyv Store` to @configu/node exports
  ts/packages/node/src/index.ts
Labels: bug

#232 Add python unit tests
  py/configu/commands/export_command.py
  py/configu/core/config_schema.py
  py/tests/commands/test_eval_command.py
  py/tests/commands/test_export_command.py
  py/tests/commands/test_upsert_command.py
  py/tests/core/test_config_schema.py
  py/tests/core/test_config_set.py
  py/tests/staticfiles/config_schemas/invalid/default_and_required.cfgu.json
  py/tests/staticfiles/config_schemas/invalid/default_and_template.cfgu.json
  py/tests/staticfiles/config_schemas/invalid/invalid_default.cfgu.json
  py/tests/staticfiles/config_schemas/invalid/nonexistent_type.cfgu.json
  py/tests/staticfiles/config_schemas/invalid/regex_missing_pattern.cfgu.json
  py/tests/staticfiles/config_schemas/invalid/reserved_names.cfgu.json
  py/tests/staticfiles/config_schemas/valid/basic.cfgu.json
  py/tests/staticfiles/config_schemas/valid/complex.cfgu.json
  py/tests/staticfiles/config_schemas/valid/empty.cfgu.json
  py/tests/stores/test_in_memory_store.py
  py/tests/stores/test_json_file_store.py
Labels: chore

#243 Feat/cfgu options support
  py/configu/commands/eval_command.py
  py/configu/commands/upsert_command.py
  py/configu/core/config_schema.py
  py/configu/core/generated.py
  ts/packages/ts/src/ConfigSchema.ts
  ts/packages/ts/src/commands/EvalCommand.ts
  ts/packages/ts/src/commands/UpsertCommand.ts
  ts/packages/ts/src/types/generated.ts
  ts/packages/vscode/public/cfgu.schema.json
  types/Cfgu.ts
Labels: feat

#248 Add `INI` `ConfigStore` to @configu/lib integrations
  ts/packages/lib/src/integrations/store.ts
Labels: chore

#249 Add `INI` `ConfigStore` to @configu/cli stores
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/helpers/stores.ts
Labels: chore

#260 Fix CLI partially upserting config values containing the `=` character
  ts/packages/cli/src/base.ts
Labels: bug
