Repository configu/configu, pull requests merged in 2024-03, with the labels that each got.

#386 Implement TOML ConfigStore in Node.js SDK
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/TomlFile.test.ts
  ts/packages/node/src/stores/TomlFile.ts
Labels: community, @configu/ts

#363 Implement Support Schema Aliasing in .configu Configuration File
  ts/packages/cli/src/base.ts
Labels: feat, @configu/cli

#379 Implement `hidden` property for Cfgu declaration with ExportCommand `filter` callback
  ts/packages/ts/src/commands/ExportCommand.ts
  ts/packages/ts/src/commands/commands.test.ts
  ts/packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: feat, @configu/core, @configu/ts

#381 Implement enhance export command with advanced filtering
  ts/package-lock.json
  ts/packages/cli/package.json
  ts/packages/cli/src/commands/export.ts
Labels: feat, @configu/cli

#385 Fix `LocalForageConfigStore` storing stringified data
  ts/packages/browser/src/stores/LocalForage.ts
Labels: bug, @configu/ts

#394 Implement CSV ConfigStore in Node.js SDK
  ts/package-lock.json
  ts/packages/node/package.json
  ts/packages/node/src/index.ts
  ts/packages/node/src/stores/CsvFile.test.ts
  ts/packages/node/src/stores/CsvFile.ts
Labels: community, @configu/ts
