Repository configu/configu, pull requests merged in 2024-10, with the labels that each got.

#469 Add Tests for ConfigSet Class #461
  packages/ts/src/ConfigSet.test.ts
Labels: hacktoberfest-accepted, community, @configu/ts

#466 Update Hacktoberfest banner to new 2024 design
  docs/images/banner/hacktoberfest-24-banner.svg
Labels: hacktoberfest-accepted, hacktoberfest

#468 Implement Slug Cfgu Type
  packages/ts/src/Cfgu.ts
  packages/ts/src/ConfigSchema.ts
  packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: hacktoberfest-accepted, community, @configu/ts

#458 Configu SDK
  .github/workflows/cd-proxy.yml
  .node-version
  .npmrc
  .nvmrc
  package.json
  packages/common/package.json
  packages/common/src/File.ts
  packages/common/src/index.ts
  packages/common/src/module.js
  packages/common/src/registry.ts
  packages/common/src/test.ts
  packages/common/tsconfig.json
  packages/proxy/package.json
  packages/sdk/README.md
  packages/sdk/package.json
  packages/sdk/src/commands/ConfigCommand.ts
  packages/sdk/src/commands/EvalCommand.ts
  packages/sdk/src/commands/ExportCommand.ts
  packages/sdk/src/commands/UpsertCommand.ts
  packages/sdk/src/commands/index.ts
  packages/sdk/src/core/Cfgu.ts
  packages/sdk/src/core/Config.ts
  packages/sdk/src/core/ConfigSchema.ts
  packages/sdk/src/core/ConfigSet.ts
  packages/sdk/src/core/ConfigStore.ts
  packages/sdk/src/core/index.ts
  packages/sdk/src/index.ts
  packages/sdk/src/stores/InMemory.ts
  packages/sdk/src/stores/Noop.ts
  packages/sdk/src/stores/index.ts
  packages/sdk/src/utils/Expression.ts
  packages/sdk/src/utils/Json.ts
  packages/sdk/src/utils/Naming.ts
  packages/sdk/src/utils/index.ts
  packages/sdk/tsconfig.json
  packages/ts/src/utils.ts
  pnpm-lock.yaml
  tsconfig.base.json
  tsconfig.bundle.json
  tsup.config.ts
Labels: @configu/cicd, @configu/ts, @configu/repo, @configu/proxy

#473 Fix broken build step
  packages/common/src/index.ts
  packages/common/src/test.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#467 Implement INI ConfigFormatter
  packages/lib/package.json
  packages/lib/src/formatters/ConfigFormat.ts
  packages/lib/src/formatters/configFormatters.ts
  packages/lib/src/formatters/formatters.test.ts
  pnpm-lock.yaml
Labels: community, @configu/lib, @configu/repo

#474 Update ci-drafter.yml
  .github/workflows/ci-drafter.yml
Labels: @configu/cicd

#475 Update ci-drafter.yml
  .github/configs/cli-release-drafter.yml
  .github/configs/lib-release-drafter.yml
  .github/configs/proxy-release-drafter.yml
  .github/configs/ts-release-drafter.yml
  .github/workflows/ci-drafter.yml
Labels: @configu/cicd

#471 Add --pretty flag to CLI export command
  packages/cli/src/commands/export.ts
  packages/lib/src/formatters/ConfigFormat.ts
  packages/lib/src/formatters/configFormatters.ts
Labels: hacktoberfest-accepted, community, @configu/lib, @configu/cli

#476 Update ci-drafter.yml
  .github/configs/cli-release-drafter.yml
  .github/configs/lib-release-drafter.yml
  .github/configs/proxy-release-drafter.yml
  .github/configs/ts-release-drafter.yml
  .github/workflows/cd-configu-integrations.yml
  packages/cli/src/commands/export.ts
Labels: @configu/cicd, @configu/cli

#494 493 - convert integrations to import sdk instead of ts lib
  README.md
  packages/browser/src/stores/LocalForage.ts
  packages/integrations/expressions/validators/tsup.config.ts
  packages/integrations/formatters/CompactJSON/tsup.config.ts
  packages/integrations/formatters/Dotenv/tsup.config.ts
  packages/integrations/formatters/HelmValues/tsup.config.ts
  packages/integrations/formatters/JSON/tsup.config.ts
  packages/integrations/formatters/KubernetesConfigMap/tsup.config.ts
  packages/integrations/formatters/TOML/tsup.config.ts
  packages/integrations/formatters/TerraformTfvars/tsup.config.ts
  packages/integrations/formatters/YAML/tsup.config.ts
  packages/integrations/package.json
  packages/integrations/src/utils/File.ts
  packages/integrations/src/utils/KeyValue.ts
  packages/integrations/stores/aws-parameter/package.json
  packages/integrations/stores/aws-parameter/src/aws-parameter.ts
  packages/integrations/stores/aws-parameter/tsup.config.ts
  packages/integrations/stores/configu/package.json
  packages/integrations/stores/configu/src/configu.ts
  packages/integrations/stores/configu/tsup.config.ts
  packages/integrations/stores/csv-file/package.json
  packages/integrations/stores/csv-file/src/csv-file.ts
  packages/integrations/stores/csv-file/tsup.config.ts
  packages/integrations/stores/hashicorp-vault/package.json
  packages/integrations/stores/hashicorp-vault/src/hashicorp-vault.ts
  packages/integrations/stores/hashicorp-vault/tsup.config.ts
  packages/integrations/stores/json-file/package.json
  packages/integrations/stores/json-file/src/json-file.ts
  packages/integrations/stores/json-file/src/utils/generated.ts
  packages/integrations/stores/json-file/tsup.config.ts
  packages/integrations/stores/sqlite/package.json
  packages/integrations/stores/sqlite/src/utils/ORM.ts
  packages/integrations/stores/sqlite/tsup.config.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/ts, @configu/repo

#479 Handle subprocess exit codes in run command
  packages/cli/src/commands/run.ts
Labels: hacktoberfest-accepted, community, @configu/cli

#492 491 - remote registry of integrations from release
  .github/workflows/cd-configu-integrations.yml
  .gitignore
  package.json
  packages/common/package.json
  packages/common/src/Registry.ts
  packages/common/src/stub/demo-store.stub.js
  packages/common/src/stub/expressions.stub.js
  packages/common/src/stub/module.js
  packages/common/src/test.ts
  packages/common/src/test/registry.test.ts
  packages/lib/src/formatters/formatters.test.ts
Labels: hacktoberfest-accepted, hacktoberfest, @configu/cicd, @configu/lib, @configu/repo

#501 typo errors in hello-world.mdx
  docs/guides/hello-world.mdx
Labels: hacktoberfest-accepted, community, @configu/docs

#497 bugfix: fix ci super slow tests run
  package.json
Labels: @configu/repo

#478 Allow provision of a default store
  packages/cli/src/base.ts
  packages/cli/src/commands/delete.ts
  packages/cli/src/commands/test.ts
  packages/cli/src/commands/upsert.ts
Labels: hacktoberfest-accepted, community, @configu/cli

#485 Implemented `CreditCard` `Cfgu Type`
  packages/ts/src/Cfgu.ts
  packages/ts/src/ConfigSchema.ts
  packages/ts/src/types/generated.ts
  types/Cfgu.ts
Labels: hacktoberfest-accepted, community, @configu/ts

#487 Implement CSV ConfigFormatter
  package.json
  packages/lib/src/formatters/ConfigFormat.ts
  packages/lib/src/formatters/configFormatters.ts
  packages/lib/src/formatters/formatters.test.ts
Labels: hacktoberfest-accepted, hacktoberfest, community, @configu/lib, @configu/repo

#499 Fix broken tests
  packages/common/src/test/registry.test.ts
Labels: hacktoberfest-accepted, community

#505 `Configs Explorer` page screenshots update
  docs/images/configs-explorer/configs-grid-menus.png
  docs/images/configs-explorer/platform-configs-explorer-sets.png
  docs/images/configs-explorer/sets-graph-menu.png
Labels: hacktoberfest-accepted, community, @configu/docs

#486 Update contributing guide according to the V1 structure
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, @configu/repo

#507 Finetune @configu/integrations
  packages/integrations/expressions/validator/package.json
  packages/integrations/expressions/validator/src/validators.ts
  packages/integrations/expressions/validator/tsup.config.ts
  packages/integrations/expressions/validator/typedoc.js
  packages/integrations/formatters/CompactJSON/package.json
  packages/integrations/formatters/Dotenv/package.json
  packages/integrations/formatters/HelmValues/package.json
  packages/integrations/formatters/JSON/package.json
  packages/integrations/formatters/KubernetesConfigMap/package.json
  packages/integrations/formatters/TOML/package.json
  packages/integrations/formatters/TerraformTfvars/package.json
  packages/integrations/formatters/YAML/package.json
  packages/integrations/package.json
  packages/integrations/src/utils/File.ts
  packages/integrations/src/utils/KeyValue.ts
  packages/integrations/src/utils/ORM.ts
  packages/integrations/stores/aws-parameter-store/package.json
  packages/integrations/stores/aws-parameter-store/src/aws-parameter-store.ts
  packages/integrations/stores/aws-parameter-store/tsconfig.json
  packages/integrations/stores/aws-parameter-store/tsup.config.ts
  packages/integrations/stores/configu/package.json
  packages/integrations/stores/configu/src/configu.ts
  packages/integrations/stores/csv-file/package.json
  packages/integrations/stores/csv-file/src/csv-file.ts
  packages/integrations/stores/hashicorp-vault/package.json
  packages/integrations/stores/hashicorp-vault/src/hashicorp-vault.ts
  packages/integrations/stores/json-file/package.json
  packages/integrations/stores/json-file/src/json-file.ts
  packages/integrations/stores/json-file/src/utils/generated.ts
  packages/integrations/stores/sqlite/package.json
  packages/integrations/stores/sqlite/src/sqlite.ts
  packages/integrations/tsconfig.json
  pnpm-lock.yaml
Labels: @configu/repo

#527 fix: remove unused build process
  package.json
Labels: hacktoberfest-accepted, @configu/repo

#536 bugfix: disable auto-splitting of aws parameter store
  packages/integrations/stores/aws-parameter-store/tsup.config.ts
Labels: hacktoberfest-accepted

#532 feat: MySQLConfigStore to @configu/integrations migration Closes #522
  packages/integrations/stores/my-sql/package.json
  packages/integrations/stores/my-sql/src/my-sql.ts
  packages/integrations/stores/my-sql/tsconfig.json
  packages/integrations/stores/my-sql/tsup.config.ts
Labels: hacktoberfest-accepted, community

#544 Fix contributing guide local development section
  CONTRIBUTING.md
Labels: @configu/repo

#539 Migrate CockroachDBConfigStore to @configu/integrations
  packages/integrations/stores/cockroach-db/package.json
  packages/integrations/stores/cockroach-db/src/cockroach-db.ts
  packages/integrations/stores/cockroach-db/tsconfig.json
  packages/integrations/stores/cockroach-db/tsup.config.ts
Labels: community

#540 Migrate AzureKeyVaultConfigStore to @configu/integrations
  packages/integrations/stores/azure-key-vault/package.json
  packages/integrations/stores/azure-key-vault/src/azure-key-vault.ts
  packages/integrations/stores/azure-key-vault/tsconfig.json
  packages/integrations/stores/azure-key-vault/tsup.config.ts
Labels: community

#531 Migrate TomlFileConfigStore to @configu/integrations
  packages/integrations/stores/toml-file/package.json
  packages/integrations/stores/toml-file/src/toml-file.ts
  packages/integrations/stores/toml-file/tsconfig.json
  packages/integrations/stores/toml-file/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#547 Fixed using the simple way suggested
  packages/cli/tsup.config.ts
  packages/integrations/expressions/validator/tsup.config.ts
  packages/integrations/formatters/CompactJSON/tsup.config.ts
  packages/integrations/formatters/Dotenv/tsup.config.ts
  packages/integrations/formatters/HelmValues/tsup.config.ts
  packages/integrations/formatters/JSON/tsup.config.ts
  packages/integrations/formatters/KubernetesConfigMap/tsup.config.ts
  packages/integrations/formatters/TOML/tsup.config.ts
  packages/integrations/formatters/TerraformTfvars/tsup.config.ts
  packages/integrations/formatters/YAML/tsup.config.ts
  packages/integrations/stores/configu/tsup.config.ts
  packages/integrations/stores/csv-file/tsup.config.ts
  packages/integrations/stores/hashicorp-vault/tsup.config.ts
  packages/integrations/stores/json-file/tsup.config.ts
  packages/integrations/stores/my-sql/tsup.config.ts
  packages/integrations/stores/sqlite/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/cli, @configu/repo

#550 initial load of integrations that are included inside the cli and proxy
  packages/common/package.json
  packages/common/src/Registry.ts
  packages/common/src/built-in-integrations.ts
  packages/common/src/index.ts
  packages/integrations/expressions/validator/package.json
  packages/integrations/formatters/CompactJSON/package.json
  packages/integrations/formatters/Dotenv/package.json
  packages/integrations/formatters/JSON/package.json
  packages/integrations/formatters/JSON/src/JSON.ts
  packages/integrations/formatters/KubernetesConfigMap/package.json
  packages/integrations/formatters/TOML/package.json
  packages/integrations/formatters/TOML/src/TOML.ts
  packages/integrations/formatters/TerraformTfvars/package.json
  packages/integrations/formatters/YAML/package.json
  packages/integrations/stores/azure-key-vault/package.json
  packages/integrations/stores/azure-key-vault/src/azure-key-vault.ts
  packages/integrations/stores/cockroach-db/package.json
  packages/integrations/stores/cockroach-db/src/cockroach-db.ts
  packages/integrations/stores/configu/package.json
  packages/integrations/stores/json-file/package.json
  packages/integrations/stores/my-sql/package.json
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/repo

#543 Add AWSSecretsManagerConfigStore to @configu/integrations
  packages/integrations/stores/aws-secrets-manager/package.json
  packages/integrations/stores/aws-secrets-manager/src/aws-secrets-manager.ts
  packages/integrations/stores/aws-secrets-manager/tsconfig.json
  packages/integrations/stores/aws-secrets-manager/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#533 Migrate MariaDBConfigStore to @configu/integrations
  packages/integrations/stores/mariadb/package.json
  packages/integrations/stores/mariadb/src/mariadb.ts
  packages/integrations/stores/mariadb/tsconfig.json
  packages/integrations/stores/mariadb/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#534 Migrate KubernetesSecretConfigStore to @configu/integrations
  packages/integrations/stores/kubernetes-secret-store/package.json
  packages/integrations/stores/kubernetes-secret-store/src/kubernetes.ts
  packages/integrations/stores/kubernetes-secret-store/tsconfig.json
  packages/integrations/stores/kubernetes-secret-store/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#552 migrate KeyvConfigStore to @configu/integrations"
  package-lock.json
  packages/integrations/stores/key-v/package.json
  packages/integrations/stores/key-v/src/keyv-store.ts
  packages/integrations/stores/key-v/tsconfig.json
  packages/integrations/stores/key-v/tsup.config.ts
Labels: community, @configu/repo

#551 add etcd to @configu/integrations
  packages/integrations/stores/etcd/package.json
  packages/integrations/stores/etcd/src/etcd.ts
  packages/integrations/stores/etcd/tsconfig.json
  packages/integrations/stores/etcd/tsup.config.ts
Labels: community

#553 fix lock file
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/repo

#560 bug: Incorrect link in readme for Explore Docs
  README.md
Labels: hacktoberfest-accepted, community, @configu/repo

#558 feat: Contributors Section to Readme with Dynamic Images
  README.md
Labels: hacktoberfest-accepted, community, @configu/repo

#529 Gcp secret manager migrate to new module
  packages/integrations/stores/gcp-secret-manager-config-store/package.json
  packages/integrations/stores/gcp-secret-manager-config-store/src/gcp-secret-manager.ts
  packages/integrations/stores/gcp-secret-manager-config-store/tsconfig.json
  packages/integrations/stores/gcp-secret-manager-config-store/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#559 Fix "Join Chat 💬" Link in README to Redirect to Discord
  README.md
Labels: hacktoberfest-accepted, community, @configu/repo

#546 Migrated MSSQLConfigStore to @configu/integrations #520
  packages/integrations/stores/ms-sql/package.json
  packages/integrations/stores/ms-sql/src/ms-sql.ts
  packages/integrations/stores/ms-sql/tsconfig.json
  packages/integrations/stores/ms-sql/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#548 Support glob patterns in .configu schema definitions
  packages/common/package.json
  packages/common/src/ConfiguFile.ts
  packages/common/src/utils.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#563 Migrate LocalForageConfigStore to @configu/integrations
  packages/integrations/stores/localforage/package.json
  packages/integrations/stores/localforage/src/localforage.ts
  packages/integrations/stores/localforage/tsconfig.json
  packages/integrations/stores/localforage/tsup.config.ts
Labels: community

#545 Complete Configu CLI - return run and test commands
  README.md
  packages/cli/src/commands/base.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/commands/test.ts
  packages/cli/src/index.ts
  packages/common/src/built-in-integrations.ts
  packages/integrations/stores/key-v/package.json
  packages/integrations/stores/key-v/src/keyv-store.ts
  packages/integrations/stores/key-v/tsconfig.json
  packages/sdk/src/commands/index.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/cli, @configu/repo

#554 feat: Implement SplitConfigStore
  packages/integrations/stores/split/package.json
  packages/integrations/stores/split/src/split.ts
  packages/integrations/stores/split/tsconfig.json
  packages/integrations/stores/split/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#564 Implemented datasize Cfgu Type
  packages/schema/.cfgu.json
Labels: community

#567 Extended Datetime Cfgu Types
  packages/schema/.cfgu.json
Labels: community

#577 fix: changed twitter icon to x
  docs/mint.json
Labels: hacktoberfest-accepted, community, @configu/docs

#570 Complete Configu CLI - Upsert command
  packages/cli/src/commands/upsert.ts
  packages/cli/src/index.ts
  packages/common/src/index.ts
  packages/sdk/src/commands/UpsertCommand.ts
Labels: hacktoberfest-accepted, @configu/cli

#565 Complete Configu CLI - Login command
  packages/cli/package.json
  packages/cli/src/commands/base.ts
  packages/cli/src/commands/login.ts
  packages/cli/src/helpers/index.ts
  packages/cli/src/helpers/utils.ts
  packages/cli/src/index.ts
  packages/common/src/ConfiguFile.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/cli, @configu/repo

#575 Add docs for `@configu-integrations/aws-secrets-manager`
  docs/images/store-examples/aws-secrets-manger/secrets-list.png
  docs/images/store-examples/aws-secrets-manger/upsert-result.png
  packages/integrations/stores/aws-secrets-manager/README.md
Labels: hacktoberfest-accepted, @configu/docs

#608 Fix `@configu-integrations/validator` registration in `@configu/common`
  packages/common/src/Registry.ts
  packages/common/src/built-in-integrations.ts
  packages/integrations/expressions/validator/src/validators.ts
Labels: hacktoberfest-accepted

#605 Migrate `PostgreSQLConfigStore` to `@configu/integrations`
  packages/integrations/stores/postgresql/README.md
  packages/integrations/stores/postgresql/package.json
  packages/integrations/stores/postgresql/src/postgresql.ts
  packages/integrations/stores/postgresql/tsconfig.json
  packages/integrations/stores/postgresql/tsup.config.ts
  pnpm-lock.yaml
Labels: community, @configu/repo

#610 Add global flags to `@configu/cli`
  packages/cli/src/commands/base.ts
Labels: @configu/cli

#568 Complete Configu CLI - Export command
  packages/cli/package.json
  packages/cli/src/commands/export.ts
  packages/cli/src/commands/run.ts
  packages/cli/src/index.ts
  packages/common/src/ConfiguFile.ts
  packages/sdk/src/utils/Expression.ts
  pnpm-lock.yaml
Labels: @configu/cli, @configu/repo

#611 Add docs for `@configu-integrations/my-sql`
  packages/integrations/stores/my-sql/README.md
Labels: community

#530 Migrate XmlFileConfigStore to @configu/integrations (issue 524)
  packages/integrations/stores/xml-file/package.json
  packages/integrations/stores/xml-file/src/xml-file.ts
  packages/integrations/stores/xml-file/tsconfig.json
  packages/integrations/stores/xml-file/tsup.config.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, community, @configu/repo

#612 docs(concepts): update links to core types
  docs/introduction/concepts.mdx
Labels: hacktoberfest-accepted, community, @configu/docs

#614 Add docs for `@configu-integrations/ms-sql`
  packages/integrations/stores/ms-sql/README.md
Labels: community

#618 Add docs for `@configu-integrations/kubernetes-secret-store`
  packages/integrations/stores/kubernetes-secret-store/README.md
Labels: hacktoberfest-accepted, community

#620 Migrate `LaunchDarklyConfigstore`
  packages/integrations/stores/launch-darkly/README.md
  packages/integrations/stores/launch-darkly/package.json
  packages/integrations/stores/launch-darkly/src/launch-darkly.ts
  packages/integrations/stores/launch-darkly/tsconfig.json
  packages/integrations/stores/launch-darkly/tsup.config.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, community, @configu/repo

#624 Add doc for `@configu-integrations/azure-keyvault`
  packages/integrations/stores/azure-key-vault/README.md
Labels: community

#626 Add doc for `@configu-integrations/split`
  packages/integrations/stores/split/README.md
Labels: hacktoberfest-accepted, community

#628 Add doc for `@configu-integrations/hashicorp-vault`
  packages/integrations/stores/hashicorp-vault/README.md
Labels: hacktoberfest-accepted, community

#602 503 - compile scripts to compile the cli to each os
  .github/workflows/cd-cli.yml
  packages/cli/.gitignore
  packages/cli/compiler/darwin.ts
  packages/cli/compiler/index.ts
  packages/cli/compiler/linux.ts
  packages/cli/compiler/win32.ts
  packages/cli/package.json
  packages/cli/sea-config.json
  packages/cli/src/commands/base.ts
  packages/cli/src/commands/login.ts
  packages/cli/src/helpers/utils.ts
  packages/common/src/Registry.ts
  packages/sdk/src/core/ConfigStore.ts
Labels: @configu/cicd, @configu/cli

#629 Add doc for `@configu-integrations/localforage`
  packages/integrations/stores/localforage/README.md
Labels: hacktoberfest-accepted, community

#630 Add doc for `@configu-integrations/keyv`
  packages/integrations/stores/key-v/README.md
Labels: hacktoberfest-accepted, community

#631 Add doc for `@configu-integrations/gcp-secret-manager`
  packages/integrations/stores/gcp-secret-manager-config-store/README.md
Labels: community

#632 Add doc for `@configu-integrations/cloud-bees`
  packages/integrations/stores/cloud-bees/README.md
Labels: hacktoberfest-accepted, community

#635 Migrate `Configu init` command to `@configu/cli`
  packages/cli/package.json
  packages/cli/src/commands/base.ts
  packages/cli/src/commands/init.ts
  packages/cli/src/helpers/configExtractor.ts
  packages/cli/src/helpers/index.ts
  packages/cli/src/helpers/utils.ts
  packages/cli/src/index.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, @configu/cli, @configu/repo

#637 Add docs for `@configu-integrations/toml-file`
  packages/integrations/stores/toml-file/README.md
Labels: hacktoberfest-accepted, community

#640 add docs for `@configu-integrations/csv-file`
  packages/integrations/stores/csv-file/README.md
Labels: hacktoberfest-accepted, community

#641 add docs for `@configu-integrations/json-file`
  packages/integrations/stores/json-file/README.md
Labels: hacktoberfest-accepted, community

#625 Migrated `IniFileConfigStore` to `@configu/integrations`
  packages/integrations/stores/ini-file/README.md
  packages/integrations/stores/ini-file/package.json
  packages/integrations/stores/ini-file/src/ini-file.ts
  packages/integrations/stores/ini-file/tsconfig.json
  packages/integrations/stores/ini-file/tsup.config.ts
  pnpm-lock.yaml
Labels: hacktoberfest-accepted, community, @configu/repo
